[build]
base = "."
command = "npm run build"
publish = "./build/"
[![Netlify Status](https://api.netlify.com/api/v1/badges/c95c68a1-c156-4de7-851e-d33db5f55931/deploy-status)](https://app.netlify.com/sites/hardcore-villani-aa908a/deploys)